version: "3.8"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=isamplesinabox
            - POSTGRES_USER=isb_writer
            - POSTGRES_DB=isb_1
        volumes:
            - pg_data:/var/lib/postgresql/data
        
    solr:
        build: ./solr/
        volumes:
            - solr_data:/var/solr
        ports:
            - "${SOLR_PORT}:8983"            
        command: solr -f -cloud
        
    isamples_inabox:
        build:
            context: ./isb/
            args:
                CRONTAB_FILE: ${CRONTAB_FILE}
                ENV_FILE: ${ENV_FILE}
                ISB_SITEMAP_PREFIX: https://${ISB_HOST}/${UVICORN_ROOT_PATH}
                
        ports:
            # In the Docker network, start on 8000 and map that to the external port specified in the environment file
            - "${ISB_PORT}:8000"
        depends_on:
            - solr
            - db
        environment:
            - ISB_UVICORN_ROOT_PATH=${UVICORN_ROOT_PATH}
            - ISB_SITEMAP_PREFIX=https://${ISB_HOST}/${UVICORN_ROOT_PATH}


    solr_schema_init:
        build: ./isb/
        depends_on:
            - isamples_inabox
            - solr
        command: python solr_schema_init/create_isb_core_schema.py    
    
volumes:
    pg_data:
        name: ${PG_VOLUME_NAME}
    solr_data:
        name: ${SOLR_VOLUME_NAME}
        