version: "3.8"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=isamplesinabox
            - POSTGRES_USER=isb_writer
            - POSTGRES_DB=isb_2
        volumes:
            - pgdata:/var/lib/postgresql/data
        
    solr:
        build: ./solr/
        volumes:
            - solrdata:/var/solr
        ports:
            - "${SOLR_PORT}:8983"
        command: solr -f -cloud
        
    isamples_inabox:
        build: ./isb/
        ports:
            # In the Docker network, start on 8000 and map that to the external port specified in the environment file
            - "${ISB_PORT}:8000"
        depends_on:
            - solr
            - db

    solr_schema_init:
        build: ./isb/
        depends_on:
            - isamples_inabox
            - solr
        command: python solr_schema_init/create_isb_core_schema.py    
    
volumes:
    pgdata:
    solrdata: