# This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

 name: Python unit tests

 on:
   push:
     branches: [ develop ]
   pull_request:
     branches: [ develop ]
   workflow_dispatch:

 jobs:
   build:

     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version: [3.9]
     

     steps:
     - name: Checkout     
       uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install Poetry
       uses: snok/install-poetry@v1
       with:
         virtualenvs-create: false
         virtualenvs-in-project: false
     - name: Poetry use system python
       run: |
         poetry env info
         poetry env use system
     - name: install pip
       run: /home/runner/.local/venv/bin/python3.9 -m pip install --upgrade pip
     - name: Hacked install of pybind11
       run: |
         /home/runner/.local/venv/bin/python3.9 -m pip install pybind11
     - name: Hacked install of fasttext
       run: |
         /home/runner/.local/venv/bin/python3.9 -m pip install fasttext
     - name: Install dependencies
       if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
       run: |
         poetry env info
         poetry env use system
         poetry env info
         poetry install --no-interaction --no-root
     - name: Install
       run: |
         poetry env info
         poetry env use system
         poetry env info         
         poetry install --no-interaction --no-root
     - name: Test with pytest
       working-directory: ./tests
       run: |
         pytest --cov --cov-fail-under=64
     - name: flake8 linter
       run:  |
         python -m flake8 --count --max-complexity 10 --ignore E501,W503 --show-source --statistics --exclude ./.venv .
     - name: Run mypy
       run: |
         pip install mypy
         mypy --install-types --non-interactive --namespace-packages
